### ISSUE TITLE
Radio towers being automatically captured

### ISSUE THREAD

**Issue by cam614** [ArmaOverthrow/Overthrow.Arma4#68] opened 2024-06-29 17:32 UTC
## Version information
- Platform:pc
- Game version:
- Overthrow version: rhs

## Describe the problem
Radio towers are being automatically captured when i go to a nearby town. Towns are also getting full support without me doing anything.

## To Reproduce
Steps to reproduce the problem:
1. delete .db file to restart
2. restart game and automatically the nearest radio tower gets captured

## Where did the issue occur?
Singleplayer 

## Additional context
using RHS mod with some weapon and forces mods

## Attach logs from the session the problem occurred in

???

Where to find logs:
- Windows - `Documents\my games\ArmaReforger\logs`

**Comment by cam614** [comment] 2024-06-29 19:04
removed all mods except for base overthrow and its dependencies, worked at first, then i exited game and came back and it automatically captured again.

**Comment by rekterakathom** [comment] 2024-06-29 21:44
I am unable to reproduce, I started a new game and loaded in multiple times and the radio towers were unaffected.

**Comment by cam614** [comment] 2024-06-29 21:46
I’ve tried uninstalling and reinstalling, verified game files, tried with
and without mods and it keeps happening. Also all the towns grow support
without me doing anything.

**Comment by blackrhino121** [comment] 2024-06-30 05:12
can confirm, had this happen to me as well using RHS.

**Comment by armazac** [comment] 2024-07-03 16:50
Should be fixed now in RHS Compatibility 1.0.7

**Closed by armazac** 2024-07-03 16:50 UTC
Labels: bug
